In [15]:
import numpy as np
import matplotlib.pyplot as plt
import sklearn
import sklearn.datasets
import sklearn.neighbors
import numpy as np
#self._model = sklearn.neighbors.BallTree(X)

rng = np.random.RandomState(0)
X = rng.random_sample((10, 3))  # 10 points in 3 dimensions
print(X)


[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]
 [0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985]
 [0.77815675 0.87001215 0.97861834]
 [0.79915856 0.46147936 0.78052918]
 [0.11827443 0.63992102 0.14335329]
 [0.94466892 0.52184832 0.41466194]]


In [17]:
tree = sklearn.neighbors.BallTree(X, leaf_size=2)              # doctest: +SKIP
dist, ind = tree.query(X[:1], k=3)                # doctest: +SKIP
print(ind)  # indices of 3 closest neighbors

print(dist)  # distances to 3 closest neighbors


[[0 3 1]]
[[0.         0.19662693 0.29473397]]
