In [95]:
import numpy as np
import matplotlib.pyplot as plt
import sklearn
import sklearn.datasets
import sklearn.neighbors
import numpy as np
#self._model = sklearn.neighbors.BallTree(X)

X = np.array([[3,1],[2,8], [2,7], [5,2],[3,2],[8,2],[2,4]])
y = np.array([[1, -1, -1, 1, -1, 1, -1]])
testPoints = np.array([[2,1], [2,6], [4, 4]])
print (testPoints[0:1])
print (testPoints[0])

[[2 6]]
[2 1]


In [25]:
model = sklearn.neighbors.BallTree(X)
#dist, ind = model.query(testPoints[:1], k=5)  
dist, ind = model.query(testPoints[:1], 5)           
print(ind)  # indices of 5 closest neighbors

print(dist)  # distances to 5 closest neighbors


[[0 4 6 3 2]]
[[1.         1.41421356 3.         3.16227766 6.        ]]


In [56]:
print(y[:1,0:4])

[[ 1 -1 -1  1]]


In [55]:
print(y[:1,5:7])

[[ 1 -1]]


In [68]:
X.shape[0]

7

In [90]:
comparisontable= np.zeros((2,2))
x[0]

array([3, 1])

In [83]:
comparisontable[1,1]=y[1]
print(comparisontable)

IndexError: index 1 is out of bounds for axis 0 with size 1